Add coverage report

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -2,29 +2,33 @@ name: Rust CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 env:
   CARGO_TERM_COLOR: always
-  
+
 jobs:
   lint-and-coverage:
     name: Lint and Coverage
     runs-on: self-hosted
 
-    environment: rpi4 
+    environment: rpi4
     env:
       CARGO_TERM_COLOR: always
       MKS_ENV_SERVO42C_UART: ${{ vars.MKS_ENV_SERVO42C_UART }}
+      GIST_SECRET: ${{ secrets.GIST_SECRET }}
+      GIST_ID: 520c3f3e52c8c80efb05f570f27bc1d2
 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
 
       - name: Install Dependencies
-        run: make install-deps
+        run: |
+          sudo apt-get install -y jq bc || echo "Apt failed, assuming tools exist"
+          make install-deps
 
       - name: Run Clippy (Lint)
         run: make lint
@@ -32,14 +36,20 @@ jobs:
       - name: Run Tests and Generate Coverage
         run: make coverage
 
-      - name: Generate Coverage Summary
+      - name: Generate Coverage & Update Gist
         run: |
-          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
-          grcov target/coverage --binary-path ./target/debug/deps/ -s . -t markdown --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" --excl-line "#\[test\]" --excl-start "mod tests \{" --excl-stop "^\}" >> $GITHUB_STEP_SUMMARY
+          REPORT=$(grcov target/coverage --binary-path ./target/debug/deps/ -s . -t markdown --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" --excl-line "#\[test\]" --excl-start "mod tests \{" --excl-stop "^\}")
 
-      - name: Upload Cobertura Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-cobertura
-          path: target/coverage/cobertura.xml
-          if-no-files-found: error
+          COVERAGE=$(echo "$REPORT" | grep -o "[0-9]\+\.[0-9]\+%" | tail -n 1 | tr -d '%')
+
+          echo "Coverage determined: $COVERAGE%"
+
+          if (( $(echo "$COVERAGE > 99" | bc -l) )); then COLOR="green";
+          elif (( $(echo "$COVERAGE > 90" | bc -l) )); then COLOR="yellow";
+          else COLOR="red"; fi
+
+          JSON_CONTENT="{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${COVERAGE}%\",\"color\":\"$COLOR\"}"
+
+          curl -L -X PATCH -H "Authorization: token $GIST_SECRET" \
+          -d "{\"files\":{\"mks-servo42-rs.json\":{\"content\": $(echo "$JSON_CONTENT" | jq -R .) }}}" \
+          https://api.github.com/gists/$GIST_ID
